FROM python:3.12.12-alpine3.23

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apk add --no-cache \
    bash \
    build-base \
    gfortran \
    musl-dev \
    openblas-dev \
    lapack-dev \
    libstdc++

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app
RUN chmod +x /app/scripts/api-entrypoint.sh

EXPOSE 8000
CMD ["/app/scripts/api-entrypoint.sh"]
